// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FilterEventsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/resources/chromedriver_win32/chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filterEventsTest() {
    // Test name: FilterEventsTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.meetup.com/");
    // 2 | setWindowSize | 1072x692 | 
    driver.manage().window().setSize(new Dimension(1072, 692));
    // 3 | runScript | window.scrollTo(0,31) | 
    js.executeScript("window.scrollTo(0,31)");
    // 4 | click | id=search-keyword-input | 
    driver.findElement(By.id("search-keyword-input")).click();
    // 5 | type | id=search-keyword-input | tennis
    driver.findElement(By.id("search-keyword-input")).sendKeys("tennis");
    // 6 | click | id=location-typeahead-searchLocation | 
    driver.findElement(By.id("location-typeahead-searchLocation")).click();
    // 7 | type | id=location-typeahead-searchLocation | New York
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys("New York");
    // 8 | mouseOver | css=.h-12 | 
    {
      WebElement element = driver.findElement(By.cssSelector(".h-12"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | css=.h-12 | 
    driver.findElement(By.cssSelector(".h-12")).click();
    // 10 | click | id=day-filter-drop-down | 
    driver.findElement(By.id("day-filter-drop-down")).click();
    // 11 | mouseOver | id=day-filter-starting-soon-option | 
    {
      WebElement element = driver.findElement(By.id("day-filter-starting-soon-option"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | id=day-filter-starting-soon-option | 
    driver.findElement(By.id("day-filter-starting-soon-option")).click();
    // 13 | mouseOut | id=day-filter-starting-soon-option | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | mouseOver | id=event-type-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.id("event-type-filter-drop-down"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | id=event-type-filter-drop-down | 
    driver.findElement(By.id("event-type-filter-drop-down")).click();
    // 16 | mouseOut | id=event-type-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | id=event-type-online-option | 
    driver.findElement(By.id("event-type-online-option")).click();
    // 18 | mouseOver | id=event-distance-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.id("event-distance-filter-drop-down"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | click | id=event-distance-filter-drop-down | 
    driver.findElement(By.id("event-distance-filter-drop-down")).click();
    // 20 | mouseOut | id=event-distance-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 21 | click | id=event-distance-25-miles-option | 
    driver.findElement(By.id("event-distance-25-miles-option")).click();
    // 22 | mouseOver | id=category-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.id("category-filter-drop-down"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | click | id=category-filter-drop-down | 
    driver.findElement(By.id("category-filter-drop-down")).click();
    // 24 | mouseOut | id=category-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 25 | click | id=metacategory-career-business-option | 
    driver.findElement(By.id("metacategory-career-business-option")).click();
    // 26 | click | css=.gl\3Awhitespace-nowrap | 
    driver.findElement(By.cssSelector(".gl\\3Awhitespace-nowrap")).click();
    // 27 | mouseOver | css=#sort-by-filter-drop-down .injected-svg | 
    {
      WebElement element = driver.findElement(By.cssSelector("#sort-by-filter-drop-down .injected-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 28 | mouseOver | id=event-distance-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.id("event-distance-filter-drop-down"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 29 | mouseOut | id=event-distance-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 30 | mouseOver | id=category-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.id("category-filter-drop-down"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 31 | click | id=category-filter-drop-down | 
    driver.findElement(By.id("category-filter-drop-down")).click();
    // 32 | mouseOut | id=category-filter-drop-down | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 33 | click | id=metacategory-new-groups-option | 
    driver.findElement(By.id("metacategory-new-groups-option")).click();
  }
}
