// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FilterGroupsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\User\\Downloads\\chromedriver_win32\\chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filterGroupsTest() {
    // Test name: FilterGroupsTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.meetup.com/");
    // 2 | setWindowSize | 1054x800 | 
    driver.manage().window().setSize(new Dimension(1054, 800));
    // 3 | runScript | window.scrollTo(0,990.4000244140625) | 
    js.executeScript("window.scrollTo(0,990.4000244140625)");
    // 4 | click | id=search-keyword-input | 
    driver.findElement(By.id("search-keyword-input")).click();
    // 5 | type | id=search-keyword-input | tennis
    driver.findElement(By.id("search-keyword-input")).sendKeys("tennis");
    // 6 | click | id=location-typeahead-searchLocation | 
    driver.findElement(By.id("location-typeahead-searchLocation")).click();
    // 7 | type | id=location-typeahead-searchLocation | New York
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys("New York");
    // 8 | sendKeys | id=location-typeahead-searchLocation | ${KEY_ENTER}
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys(Keys.ENTER);
    // 9 | click | id=find-groups-tab | 
    driver.findElement(By.id("find-groups-tab")).click();
    // 10 | click | id=event-distance-filter-drop-down | 
    driver.findElement(By.id("event-distance-filter-drop-down")).click();
    // 11 | click | id=event-distance-filter-drop-down | 
    driver.findElement(By.id("event-distance-filter-drop-down")).click();
    // 12 | click | id=event-distance-50-miles-option | 
    driver.findElement(By.id("event-distance-50-miles-option")).click();
    // 13 | click | id=category-filter-drop-down | 
    driver.findElement(By.id("category-filter-drop-down")).click();
    // 14 | click | id=metacategory-community-environment-option | 
    driver.findElement(By.id("metacategory-community-environment-option")).click();
    // 15 | mouseOver | id=group-card-in-search-results | 
    {
      WebElement element = driver.findElement(By.id("group-card-in-search-results"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | click | css=.gl\3Awhitespace-nowrap | 
    driver.findElement(By.cssSelector(".gl\\3Awhitespace-nowrap")).click();
  }
}
