// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FilterEventsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/resources/chromedriver_win32/chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void filterEventsTest1() {
    // Test name: FilterEventsTest (1)
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.meetup.com/");
    // 2 | setWindowSize | 1072x692 | 
    driver.manage().window().setSize(new Dimension(1072, 692));
    // 3 | runScript | window.scrollTo(0,31) | 
    js.executeScript("window.scrollTo(0,31)");
    // 4 | click | xpath=//input[@id='search-keyword-input'] | 
    driver.findElement(By.xpath("//input[@id=\'search-keyword-input\']")).click();
    // 5 | type | xpath=//input[@id='search-keyword-input'] | tennis
    driver.findElement(By.xpath("//input[@id=\'search-keyword-input\']")).sendKeys("tennis");
    // 6 | click | xpath=//input[@id='location-typeahead-searchLocation'] | 
    driver.findElement(By.xpath("//input[@id=\'location-typeahead-searchLocation\']")).click();
    // 7 | type | xpath=//input[@id='location-typeahead-searchLocation'] | New York
    driver.findElement(By.xpath("//input[@id=\'location-typeahead-searchLocation\']")).sendKeys("New York");
    // 8 | mouseOver | xpath=//input[@value='Поиск'] | 
    {
      WebElement element = driver.findElement(By.xpath("//input[@value=\'Поиск\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | xpath=//input[@value='Поиск'] | 
    driver.findElement(By.xpath("//input[@value=\'Поиск\']")).click();
    // 10 | click | xpath=//button[@id='day-filter-drop-down'] | 
    driver.findElement(By.xpath("//button[@id=\'day-filter-drop-down\']")).click();
    // 11 | mouseOver | xpath=//button[@id='day-filter-starting-soon-option'] | 
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'day-filter-starting-soon-option\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | click | xpath=//button[@id='day-filter-starting-soon-option'] | 
    driver.findElement(By.xpath("//button[@id=\'day-filter-starting-soon-option\']")).click();
    // 13 | mouseOut | xpath=//button[@id='day-filter-starting-soon-option'] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 14 | mouseOver | xpath=//button[@id='event-type-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'event-type-filter-drop-down\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 15 | click | xpath=//button[@id='event-type-filter-drop-down'] | 
    driver.findElement(By.xpath("//button[@id=\'event-type-filter-drop-down\']")).click();
    // 16 | mouseOut | xpath=//button[@id='event-type-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 17 | click | xpath=//button[@id='event-type-online-option'] | 
    driver.findElement(By.xpath("//button[@id=\'event-type-online-option\']")).click();
    // 18 | mouseOver | xpath=//button[@id='event-distance-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'event-distance-filter-drop-down\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | click | xpath=//button[@id='event-distance-filter-drop-down'] | 
    driver.findElement(By.xpath("//button[@id=\'event-distance-filter-drop-down\']")).click();
    // 20 | mouseOut | xpath=//button[@id='event-distance-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 21 | click | xpath=//button[@id='event-distance-25-miles-option'] | 
    driver.findElement(By.xpath("//button[@id=\'event-distance-25-miles-option\']")).click();
    // 22 | mouseOver | xpath=//button[@id='category-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'category-filter-drop-down\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 23 | click | xpath=//button[@id='category-filter-drop-down'] | 
    driver.findElement(By.xpath("//button[@id=\'category-filter-drop-down\']")).click();
    // 24 | mouseOut | xpath=//button[@id='category-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 25 | click | xpath=//button[@id='metacategory-career-business-option'] | 
    driver.findElement(By.xpath("//button[@id=\'metacategory-career-business-option\']")).click();
    // 26 | click | xpath=//main[@id='main']/div/div/div[2]/div/div[6]/button | 
    driver.findElement(By.xpath("//main[@id=\'main\']/div/div/div[2]/div/div[6]/button")).click();
    // 27 | mouseOver | css=#sort-by-filter-drop-down .injected-svg | 
    {
      WebElement element = driver.findElement(By.cssSelector("#sort-by-filter-drop-down .injected-svg"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 28 | mouseOver | xpath=//button[@id='event-distance-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'event-distance-filter-drop-down\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 29 | mouseOut | xpath=//button[@id='event-distance-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 30 | mouseOver | xpath=//button[@id='category-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.xpath("//button[@id=\'category-filter-drop-down\']"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 31 | click | xpath=//button[@id='category-filter-drop-down'] | 
    driver.findElement(By.xpath("//button[@id=\'category-filter-drop-down\']")).click();
    // 32 | mouseOut | xpath=//button[@id='category-filter-drop-down'] | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 33 | click | xpath=//button[@id='metacategory-new-groups-option'] | 
    driver.findElement(By.xpath("//button[@id=\'metacategory-new-groups-option\']")).click();
  }
}
