// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchGroupsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "src/resources/chromedriver_win32/chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchGroupsTest() {
    // Test name: SearchGroupsTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.meetup.com/");
    // 2 | setWindowSize | 1072x693 | 
    driver.manage().window().setSize(new Dimension(1072, 693));
    // 3 | runScript | window.scrollTo(0,15.199999809265137) | 
    js.executeScript("window.scrollTo(0,15.199999809265137)");
    // 4 | click | id=search-keyword-input | 
    driver.findElement(By.id("search-keyword-input")).click();
    // 5 | type | id=search-keyword-input | tennis
    driver.findElement(By.id("search-keyword-input")).sendKeys("tennis");
    // 6 | click | id=location-typeahead-searchLocation | 
    driver.findElement(By.id("location-typeahead-searchLocation")).click();
    // 7 | type | id=location-typeahead-searchLocation | new york
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys("new york");
    // 8 | click | css=.h-12 | 
    driver.findElement(By.cssSelector(".h-12")).click();
    // 9 | click | id=find-groups-tab | 
    driver.findElement(By.id("find-groups-tab")).click();
    // 10 | click | css=.w-full:nth-child(1) > .py-3 .d1xev8qx > .object-cover | 
    driver.findElement(By.cssSelector(".w-full:nth-child(1) > .py-3 .d1xev8qx > .object-cover")).click();
    // 11 | runScript | window.scrollTo(0,1310.4000244140625) | 
    js.executeScript("window.scrollTo(0,1310.4000244140625)");
    // 12 | runScript | window.scrollTo(0,571.2000122070312) | 
    js.executeScript("window.scrollTo(0,571.2000122070312)");
    // 13 | click | css=.event-share-email > img | 
    driver.findElement(By.cssSelector(".event-share-email > img")).click();
  }
}
