// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchGroupsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\User\\Downloads\\chromedriver_win32\\chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchGroupsTest() {
    // Test name: SearchGroupsTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.meetup.com/");
    // 2 | setWindowSize | 1062x800 | 
    driver.manage().window().setSize(new Dimension(1062, 800));
    // 3 | click | id=search-keyword-input | 
    driver.findElement(By.id("search-keyword-input")).click();
    // 4 | type | id=search-keyword-input | tennis
    driver.findElement(By.id("search-keyword-input")).sendKeys("tennis");
    // 5 | click | id=location-typeahead-searchLocation | 
    driver.findElement(By.id("location-typeahead-searchLocation")).click();
    // 6 | type | id=location-typeahead-searchLocation | New York
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys("New York");
    // 7 | sendKeys | id=location-typeahead-searchLocation | ${KEY_ENTER}
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys(Keys.ENTER);
    // 8 | mouseOver | id=find-groups-tab | 
    {
      WebElement element = driver.findElement(By.id("find-groups-tab"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 9 | click | id=find-groups-tab | 
    driver.findElement(By.id("find-groups-tab")).click();
    // 10 | mouseOut | id=find-groups-tab | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 11 | mouseOver | id=group-card-in-search-results | 
    {
      WebElement element = driver.findElement(By.id("group-card-in-search-results"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 12 | mouseOut | id=group-card-in-search-results | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 13 | click | css=.w-full:nth-child(1) > .py-3 .d1xev8qx > .object-cover | 
    driver.findElement(By.cssSelector(".w-full:nth-child(1) > .py-3 .d1xev8qx > .object-cover")).click();
    // 14 | click | css=.event-share-email > img | 
    driver.findElement(By.cssSelector(".event-share-email > img")).click();
  }
}
