// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SearchEventsTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\User\\Downloads\\chromedriver_win32\\chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void searchEventsTest() {
    // Test name: SearchEventsTest
    // Step # | name | target | value
    // 1 | open | / | 
    driver.get("https://www.meetup.com/");
    // 2 | setWindowSize | 1058x800 | 
    driver.manage().window().setSize(new Dimension(1058, 800));
    // 3 | runScript | window.scrollTo(0,1531.199951171875) | 
    js.executeScript("window.scrollTo(0,1531.199951171875)");
    // 4 | click | id=search-keyword-input | 
    driver.findElement(By.id("search-keyword-input")).click();
    // 5 | type | id=search-keyword-input | games
    driver.findElement(By.id("search-keyword-input")).sendKeys("games");
    // 6 | click | id=location-typeahead-searchLocation | 
    driver.findElement(By.id("location-typeahead-searchLocation")).click();
    // 7 | type | id=location-typeahead-searchLocation | New York
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys("New York");
    // 8 | sendKeys | id=location-typeahead-searchLocation | ${KEY_ENTER}
    driver.findElement(By.id("location-typeahead-searchLocation")).sendKeys(Keys.ENTER);
    // 9 | click | css=div:nth-child(1) > .p-0 > #event-card-in-search-results .rounded-t-lg | 
    driver.findElement(By.cssSelector("div:nth-child(1) > .p-0 > #event-card-in-search-results .rounded-t-lg")).click();
    // 10 | runScript | window.scrollTo(0,64) | 
    js.executeScript("window.scrollTo(0,64)");
    // 11 | runScript | window.scrollTo(0,340) | 
    js.executeScript("window.scrollTo(0,340)");
    // 12 | runScript | window.scrollTo(0,592) | 
    js.executeScript("window.scrollTo(0,592)");
    // 13 | click | css=.ml-8:nth-child(1) .flex:nth-child(4) > .text-sm:nth-child(1) | 
    driver.findElement(By.cssSelector(".ml-8:nth-child(1) .flex:nth-child(4) > .text-sm:nth-child(1)")).click();
    // 14 | runScript | window.scrollTo(0,23.200000762939453) | 
    js.executeScript("window.scrollTo(0,23.200000762939453)");
    // 15 | runScript | window.scrollTo(0,388.79998779296875) | 
    js.executeScript("window.scrollTo(0,388.79998779296875)");
    // 16 | runScript | window.scrollTo(0,615.2000122070312) | 
    js.executeScript("window.scrollTo(0,615.2000122070312)");
    // 17 | runScript | window.scrollTo(0,266.3999938964844) | 
    js.executeScript("window.scrollTo(0,266.3999938964844)");
    // 18 | click | css=.px-2:nth-child(2) | 
    driver.findElement(By.cssSelector(".px-2:nth-child(2)")).click();
    // 19 | click | css=.list-style-none:nth-child(5) .ml-2 | 
    driver.findElement(By.cssSelector(".list-style-none:nth-child(5) .ml-2")).click();
    // 20 | click | css=.hidden > #close .injected-svg | 
    driver.findElement(By.cssSelector(".hidden > #close .injected-svg")).click();
  }
}
