// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.time.Duration;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SignUpTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    System.setProperty("webdriver.chrome.driver", "C:\\Users\\User\\Downloads\\chromedriver_win32\\chromedriver.exe");

    ChromeOptions options = new ChromeOptions();
    options.addArguments("--remote-allow-origins=*");

    driver = new ChromeDriver(options);
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void signUpTest() {
    driver.get("https://www.meetup.com/");
    driver.manage().window().setSize(new Dimension(1053, 799));
    //driver.findElement(By.id("register-link")).click();
    driver.findElement(By.xpath("//a[@id='register-link']")).click();
    {
      WebElement element = driver.findElement(By.id("email-register"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    //driver.findElement(By.id("email-register")).click();
    //driver.findElement(By.id("name")).sendKeys("Anna");
    //driver.findElement(By.id("email")).sendKeys("anna@mail.ru");
    //driver.findElement(By.id("new-password")).click();
    //driver.findElement(By.id("new-password")).sendKeys("Kas1chka22");
    driver.findElement(By.xpath("//button[@id='email-register']")).click();
    driver.findElement(By.xpath("//input[@id='name']")).sendKeys("Anna");
    driver.findElement(By.xpath("//input[@id='email']")).sendKeys("anna@mail.ru");
    driver.findElement(By.xpath("//input[@id='new-password']")).click();

    driver.findElement(By.xpath("//input[@id='new-password']")).sendKeys("Kas1chka223");
    driver.switchTo().frame(2);
    driver.switchTo().defaultContent();
    //driver.findElement(By.name("submitRegistrationButton")).click();
    driver.findElement(By.xpath("//button[@name='submitRegistrationButton']")).click();
    js.executeScript("window.scrollTo(0,140.8000030517578)");
  }
}
